version: '2'
services:
  web:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      db:
        condition: service_healthy
        restart: true
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgress
      - POSTGRES_DB=irisdb

  db:
    image: postgres
    restart: always
    shm_size: 128mb
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgress
      - POSTGRES_DB=irisdb
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d irisdb"]
      interval: 5s
      retries: 5
      start_period: 30s
      timeout: 10s
    volumes:
      - ./postgresql-data:/var/lib/postgresql/data
